[toolchain]
anchor_version = "0.30.1"
solana_version = "1.18.18"

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_program = "5FwvYgAChMwMsBrmSKBBZeWRGX27p62G3o3UsBQjhVJZ"
nft_game_agent_program = "7SKb68VU9C8Pmjip67q7xDjqnLekaUUNA7gM8AB5MDxN"
freedumbs_controller_program = "FreeD5yGkRZsVu8RYkeFhPNpVX3ea3T6baqWzAs4zqRj"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/new_program_keypair.json"

[workspace]
members = ["programs/nft_game_agent_program", "programs/betting_program", "programs/freedumbs_controller_program"]

[scripts]
test = "npm run test:mocha"

[test]
startup_wait = 30000
shutdown_wait = 5000
upgradeable = true
