[toolchain]
anchor_version = "0.30.1"
solana_version = "2.0.23"

[features]
resolution = true
skip-lint = false

[programs.devnet]
betting_program = "GYLtHxFn26XJr9fcHgC28r2mPR64sUQqVu3EMfQ4FzER"
nft_game_agent_program = "2HuYN4A2wYEiTpP7tdx4rKKcLPauwDwwchjxgMkM3gJ3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/new_program_keypair.json"

[workspace]
members = ["programs/betting_program", "programs/nft_game_agent_program"]

[scripts]
test = "npm run test:mocha"

[test]
startup_wait = 30000
shutdown_wait = 5000
upgradeable = true
