[workspace]
resolver = "2"
members = [
    "programs/*"
]

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
incremental = false

[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1

